### ISSUE TITLE
git error: No stash entries found.

### ISSUE THREAD

**Issue by jmichalak-fluxninja** [ejoffe/spr#100]
This happened when I typed `git spr u` and I didn't have any stashed changes. The branch on remote was updated, but the pull request wasn't created. Detailed logs: 
```
git error: No stash entries found.
panic: exit status 1

goroutine 1 [running]:
github.com/ejoffe/spr/spr.check(...)
	/Users/eitan/Code/spr/spr/spr.go:425
github.com/ejoffe/spr/spr.(*stackediff).mustgit(0xc0001a4550, 0x842ad0, 0x9, 0x0)
	/Users/eitan/Code/spr/spr/spr.go:420 +0x86
github.com/ejoffe/spr/spr.(*stackediff).syncCommitStackToGitHub(0xc0001a4550, 0x8c25b0, 0xc00001a140, 0xc00057e000, 0x3, 0x4, 0xc0003da5a0)
	/Users/eitan/Code/spr/spr/spr.go:412 +0x5a5
github.com/ejoffe/spr/spr.(*stackediff).UpdatePullRequests(0xc0001a4550, 0x8c25b0, 0xc00001a140)
	/Users/eitan/Code/spr/spr/spr.go:102 +0x3c6
main.main.func3(0xc000188d80, 0x2, 0x2)
	/Users/eitan/Code/spr/cmd/spr/main.go:139 +0x3c
github.com/urfave/cli/v2.(*Command).Run(0xc000246120, 0xc000188c80, 0x0, 0x0)
	/Users/eitan/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc000194d00, 0x8c25b0, 0xc00001a140, 0xc00018c000, 0x2, 0x2, 0x0, 0x0)
	/Users/eitan/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/eitan/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/Users/eitan/Code/spr/cmd/spr/main.go:174 +0xc77
```
The workaround is to create a dummy stash entry, but after the `git spr u` it's popped from the stack, which is inconvenient.

**Comment by ejoffe** [comment]
What version are you using? 
`> git spr --version`

**Comment by jmichalak-fluxninja** [comment]
`0.7.6 : 2021-09-26T20:22:29Z : ac0b6503` but it happened several times while I was using 0.7.5 too.

**Comment by ejoffe** [comment]
Thank you. I'll try to reproduce this locally. 
If you can have a run where this happens with logging enabled, that could help out. In your user config in ~/.spr.yml
```
logGitCommands: true
logGitHubCalls: true
```

**Comment by ejoffe** [comment]
From code inspection it looks like spr is trying to call `git stash pop` on line 386 in the deferred call but the stash is empty. 
One way I guess this could happened is if `git status --porcelain --untracked-files=no` returns something while the stash is empty, which is unexpected. 
A workaround to this could be to ignore the error of popping an empty stash, and treat it as a noop. 
But would be better to understand in your case what `git status --porcelain --untracked-files=no` is returning so we can fix the root cause.

**Comment by jmichalak-fluxninja** [comment]
`git status --porcelain --untracked-files=no` returns nothing. But ironically now `git spr u` works correctly. I will try to run this porcelain command when stash error occurs. This error doesn't always happen, so it may be hard to reproduce. Anyway, thx for help.

**Comment by ejoffe** [comment]
Ok, if it happens again, try to run the git status command, and let's see.

**Comment by ejoffe** [comment]
Closing as this has been stale for a while.
