### ISSUE TITLE
Support `.netrc` for sourcing GITHUB_TOKEN

### ISSUE THREAD

**Issue by abatilo** [ejoffe/spr#114]
It's common to configuration GH authentication with a PAT that you place into your `.netrc` file. It would be great if spr could source from there instead of requiring an env variable

**Comment by ejoffe** [comment]
This sounds great. I don't have the env to test this, if you are up for it, pull request is more than welcomed.

**Comment by chriscz** [comment]
I've been using an alias for this
```
alias git-spr="OVERCOMMIT_DISABLED=1 GITHUB_TOKEN=XXX /usr/local/bin/git-spr"
```
