### ISSUE TITLE
`git spr update` does not close PRs that were manually fixup'd

### ISSUE THREAD

**Issue by abatilo** [ejoffe/spr#118]
When I had `panic`s for previous `git amend` attempts, I was left with fixup commits that opened PRs and I had no way of consolidating them and close the PR automatically. After doing a manual `fixup`, I just had to go close the PRs. Maybe there could be a way to do like a `git spr clean` which will look at all the current commits and commit IDs and close any PRs that don't have a matching commit ID?

**Comment by ejoffe** [comment]
@abatilo : I am in favor of the idea that 'git spr update' takes the list of commits on top of origin/master and fully syncs those with github. By fully sync I mean, create a new pr for any new commint, update prs for amended commits, and delete prs for commits that were removed. 
Currently, we do the first two but we don't delete prs in github for commits that have been removed, but if we would, I think it would take care of both this issue and #117 without introducing a new command. 
The tricky part is figuring out which prs belong to the current branch you are working on, and not removing unrelated prs from other branches or repositories. I'll look deeper into what this takes.

**Comment by ejoffe** [comment]
@abatilo - I just published a [pr](http://github.com/ejoffe/spr/pull/122) to automatically close pull requests when a commit is removed from the stack. I'll release this soon after I run it through some local testing.

**Comment by ejoffe** [comment]
fix released in v0.7.14 - orphaned pull requests now get closed on 'git spr update'

**Comment by ejoffe** [comment]
closing this issue as spr now automatically closes prs when a commit is removed.
