### ISSUE TITLE
Visualize the stack in the PR description

### ISSUE THREAD

**Issue by leoluk** [ejoffe/spr#139]
[ghstack](https://github.com/ezyang/ghstack) has a nice feature visualizing the stack:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/859697/144301788-c2c52a67-af48-49c3-8e4f-95ba0c1f29d1.png">

Large stacks are usually reviewed in order, so this would be a useful feature to have (or perhaps it already does and I just didn't know how to turn it on?)

**Comment by ejoffe** [comment]
The current output of the spr command is the stack, not sure how else to visualize it?

sample output:
`[✗✗✔✗] 522 : top change
[✗✗✔✗] 521 : more change
[·✗✔✗] 520 : next change
[·✗✔✗] 519 : bottom change`

**Comment by leoluk** [comment]
> I guess you might be thinking of visualizing the stacks on the github pull requests page?

Yep - that's what I meant, making it easier to navigate within the stack during review.

**Comment by ejoffe** [comment]
I see, it edits the pr body and adds the whole stack info in there. 
That's really cool, and would be a super cool feature to add to spr!

**Comment by ejoffe** [comment]
released in v0.8.0
