### ISSUE TITLE
Allow specifying reviewers for spr update

### ISSUE THREAD

**Issue by leoluk** [ejoffe/spr#145]
Gerrit has a neat feature where you can specify reviewers when pushing:

    git push origin HEAD:refs/for/main%r=leo

(with fuzzy matching for the username)

spr could emulate this and allow specifying a `spr update -r leo` parameter to set the default reviewer for all commits in the stack.

**Comment by ejoffe** [comment]
another option is to look in the commit message for some pattern such as: "reviewer: xxxx".
similar to tagging pull requests with fixed and other tags.

**Comment by leoluk** [comment]
> another option is to look in the commit message for some pattern such as: "reviewer: xxxx".

I thought about that, but that would get out of sync with the reviewer list in the UI

> spr update may be called many times for a particular stack, and the stack might have different reviewers for different commits, so that might get confusing.

Idea is to only add the reviewers when creating the stack, allowing for manual fine tuning in the UI - that's how I use the Gerrit workflow. 90% of the time, the reviewer list is the same for the entire stack, and for the remaining 10%, I just leave it empty and add reviewers manually through the UI.

**Comment by ejoffe** [comment]
Cool. I'm a fan of this as a quick way to assign reviewers.
We can add other ways to set reviewers with more granular controls in the future as well.

**Comment by wade13** [comment]
I started hacking on the UI but timed out at the "find IDs for reviewers" in `UpdatePullRequest`.

```go
func (c *client) UpdatePullRequest(ctx context.Context,
	info *github.GitHubInfo, pr *github.PullRequest, commit git.Commit, prevCommit *git.Commit) {
```

I will probably look again later, but if anyone is more familiar (see [UpdateIssueInput.assigneeIds](https://docs.github.com/en/graphql/reference/input-objects#updateissueinput)) then that'd be neat, too :smile: 

I'm assuming it's the result of some [user queries](https://docs.github.com/en/graphql/reference/queries#user).

**Comment by ejoffe** [comment]
I scanned the github graphql docs, and I don't see a way to get a user's node_id using the graphql api, this seems very odd. It would be quite unfortunate if that's not possible. 
This page mentions getting node_ids from the rest api and using them in graphql : https://docs.github.com/en/graphql/guides/using-global-node-ids. 
If it's not possible to fetch users node_ids using graphql, I guess we could use the rest api to do that, and then the graphql api to assign the reviewer. 
Note that you'll want to use UpdatePullRequestInput - not UpdateIssueInput. 
We should only apply a reviewer to new pull requests and avoid updating other pull requests that are in the stack. 
Unfortunately it looks like the CreatePullRequest api doesn't have reviewers, so we'll have to call CreatePullRequest followed by UpdatePullRequest.

**Comment by wwade** [comment]
I had a look at the [cli/cli](http://github.com/cli/cli) implementation of `gh` and figured out how to do it wth graphql. Basically, they pull down the list of assignable users first, and then compare the usernames in the list to find the IDs.

Regarding the semantics of the option, we could use the `Union: true` flag and affect the entire stack, but I guess like you said, we could do this later with a more granular flag. For now, it's probably fine to just add to new PRs, so I'll go ahead with that approach.

For later reference, in [cli/cli/pkg/cmd/pr/edit/edit.go](https://github.com/cli/cli/blob/trunk/pkg/cmd/pr/edit/edit.go#L230):
```go
	reviewsRequestParams := githubv4.RequestReviewsInput{
		PullRequestID: id,
		Union:         &union,
		UserIDs:       ghIds(userIds),
		TeamIDs:       ghIds(teamIds),
	}
```
