### ISSUE TITLE
Marking a commit WIP after-the-fact seems to lead to confusion

### ISSUE THREAD

**Issue by leoluk** [ejoffe/spr#157]
I marked the top commit on this stack WIP and inserted another commit beneath it:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/859697/145817984-7058c587-5698-41ce-bbf9-223858720b8a.png">

... which somehow lead to this PRs body changing:

https://github.com/ejoffe/spr/pull/155

<img width="502" alt="image" src="https://user-images.githubusercontent.com/859697/145818093-245cd1b6-8c5a-4f77-9bbf-7ff039d68119.png">

... to the old message of https://github.com/ejoffe/spr/pull/147. Not sure what happened here?

Removing the "WIP" title and re-running spr undid the damage.

**Comment by ejoffe** [comment]
This code path is untested and very minimally used, so I can't say I'm surprised there is some weird behavior. 
If I have some spare cycles in the next couple of weeks, I'll look into this.

**Comment by ejoffe** [comment]
@leoluk - I recently also ran into an issue in this area. My current thinking is to completely ignore all commits in the stack starting from the WIP commit. This means that if you have a bunch of PRs in the stack and mark some PR in the middle as WIP, spr update will close all the PRs starting from the WIP going upwards. 
I think this is correct behavior and avoids weird corner cases, but might lead to surprising results (prs closing that don't have wip but are above a wip pr). Thoughts?

**Comment by leoluk** [comment]
There's no point to have a non-WIP PR on top of a WIP one so this makes sense to me.

**Comment by ejoffe** [comment]
I think this is fixed now.
