### ISSUE TITLE
Add --upto merge flag

### ISSUE THREAD

**Issue by leoluk** [ejoffe/spr#158]
> One other option that might make this a bit easier is to add a flag: `git spr merge --upto 123` which will make git spr only merge part of the stack up to that pr. This way one can merge a batch of changes with the same reviewer in one call, then wait for actions to run, and merge the next batch.

_Originally posted by @ejoffe in https://github.com/ejoffe/spr/issues/98#issuecomment-985531063_

This would be awesome to have - many times, you want to merge the "lower" parts of the stack while the "top" parts are still under review. Right now, this doesn't seem to be possible (or is it?)

**Comment by ejoffe** [comment]
released in v0.8.1
