### ISSUE TITLE
Weird behavior when trying to land stack

### ISSUE THREAD

**Issue by leoluk** [ejoffe/spr#174]
I tried to land the current stack, and this happened:

<pre>
(minikube) (develop) spr $ git spr status 
> git rev-parse --show-toplevel
> git status --porcelain
> git remote -v

 ┌─ github checks pass
 │ ┌── pull request approved
 │ │ ┌─── no merge conflicts
 │ │ │ ┌──── stack check
 │ │ │ │
[❌➖✅❌] https://github.com/ejoffe/spr/pull/155 : Use emojis for "spr status" output <b><-- I dropped this one from my local branch</b>
[✅➖✅✅] https://github.com/ejoffe/spr/pull/156 : Support the "gh" CLI tool in addition to "hub"
[✅➖✅✅] https://github.com/ejoffe/spr/pull/154 : Only update run count when user is not already a stargazer
[✅➖✅✅] https://github.com/ejoffe/spr/pull/153 : Do not panic on runtime errors
[✅➖✅✅] https://github.com/ejoffe/spr/pull/152 : Manual merge notice
[✅➖✅✅] https://github.com/ejoffe/spr/pull/151 : README.md: document how to install from source
[✅➖✅✅] https://github.com/ejoffe/spr/pull/150 : Wrap commit body in code area in PR message
[✅➖✅✅] https://github.com/ejoffe/spr/pull/149 : Mark current position in stack
[✅➖✅✅] https://github.com/ejoffe/spr/pull/148 : Include https:// in PR link
[✅➖✅✅] https://github.com/ejoffe/spr/pull/147 : Reformat PR comment messages

(minikube) (develop) spr $ git spr merge 
> git rev-parse --show-toplevel
> git status --porcelain
> git remote -v
MERGED https://github.com/ejoffe/spr/pull/147 : Reformat PR comment messages
MERGED https://github.com/ejoffe/spr/pull/148 : Include https:// in PR link
MERGED https://github.com/ejoffe/spr/pull/149 : Mark current position in stack
MERGED https://github.com/ejoffe/spr/pull/150 : Wrap commit body in code area in PR message
MERGED https://github.com/ejoffe/spr/pull/151 : README.md: document how to install from source
MERGED https://github.com/ejoffe/spr/pull/152 : Manual merge notice
MERGED https://github.com/ejoffe/spr/pull/153 : Do not panic on runtime errors
MERGED https://github.com/ejoffe/spr/pull/154 : Only update run count when user is not already a stargazer
MERGED https://github.com/ejoffe/spr/pull/156 : Support the "gh" CLI tool in addition to "hub"
panic: was submitted too quickly

goroutine 1 [running]:
github.com/ejoffe/spr/github/githubclient.check({0x8774c0, 0xc00012aae0})
	/home/leopold/projects/spr/github/githubclient/client.go:542 +0xfa
github.com/ejoffe/spr/github/githubclient.(*client).CreatePullRequest(0xc0002b1f90, {0x87f370, 0xc00001c128}, 0xc00008e050, {{0xc00013a5ed, 0x8}, {0xc00013a4a0, 0x28}, {0xc00013a51f, 0x13}, ...}, ...)
	/home/leopold/projects/spr/github/githubclient/client.go:307 +0x5d5
github.com/ejoffe/spr/spr.(*stackediff).UpdatePullRequests(0xc00068f200, {0x87f370, 0xc00001c128})
	/home/leopold/projects/spr/spr/spr.go:161 +0xa98
main.main.func4(0xc00031aa20)
	/home/leopold/projects/spr/cmd/spr/main.go:151 +0x48
github.com/urfave/cli/v2.(*Command).Run(0xc0003187e0, 0xc0002b9200)
	/home/leopold/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc0001036c0, {0x87f370, 0xc00001c128}, {0xc000012040, 0x2, 0x2})
	/home/leopold/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
	/home/leopold/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/leopold/projects/spr/cmd/spr/main.go:174 +0xde5
</pre>

Even though it worked, it got confused and created a new set of PRs for stuff already landed:

- https://github.com/ejoffe/spr/pull/173 : README.md: document how to install from source
- https://github.com/ejoffe/spr/pull/172 : Wrap commit body in code area in PR message
- https://github.com/ejoffe/spr/pull/171 : Mark current position in stack
- https://github.com/ejoffe/spr/pull/170 : Include https:// in PR link
- https://github.com/ejoffe/spr/pull/169 : Reformat PR comment messages

It also closed this one because the local commit went away (fair enough, what is the proper way to land only parts of a stack?):

- https://github.com/ejoffe/spr/pull/155

This happened after https://github.com/ejoffe/spr/issues/168, when I switched back to my local branch `develop`.

**Comment by ejoffe** [comment]
Closing as this hasn't trigger in a while, perhaps due to adding more crud which slows stuff down enough.
