### ISSUE TITLE
Landing a stack causes reviews to be dismissed on the top stack

### ISSUE THREAD

**Issue by leoluk** [ejoffe/spr#176]
When landing a stack, when changing the top PR's base, reviews get dismissed automatically when "Dismiss stale pull request approvals when new commits are pushed" is enabled.

![image](https://user-images.githubusercontent.com/859697/146797330-2f42223d-39ef-4747-897d-3c072b0555b6.png)

This breaks the workflow in repos with that option enabled. Honestly not sure what to do about it, though...

**Comment by ejoffe** [comment]
This is a limitation of the current design.
