### ISSUE TITLE
Avoid creating duplicate PRs on a different branch

### ISSUE THREAD

**Issue by leoluk** [ejoffe/spr#192]
When switching to a different local branch, all upstream PRs will be recreated with a different branch name.

At the very least, we should display an error and refuse.

**Comment by schreter** [comment]
Wouldn't the easiest way be to simply remove the local branch name from the remote branch?

I.e., instead of using `pr/<user>/<local_branch>/<commit_id>` use just `pr/<user>/<commit_id>`?

That could be probably added using a config option, also for testing purposes.

**Comment by ejoffe** [comment]
This is by design. 
Each branch should be viewed as a different stack of pull requests. 
I usually use different branches for different major features that are unrelated and don't depend on each other.

**Comment by ejoffe** [comment]
cleaning up old issues. closing this as won't fix.
