### ISSUE TITLE
Provide an argument for "update" to limit the number of PRs updated

### ISSUE THREAD

**Issue by wwade** [ejoffe/spr#212]
I keep running into a fairly typcial case where I have a stack of, say, 4 commits

pull/4
pull/3 
pull/2
pull/1

I'm working on more on this branch, but I'm not ready to post them for review. In the meantime, a helpful reviewer has commented on pull/2 and I'd like to post my modified PR2 in response, but not update any of 3, 4 and my WIP stack.

The suggestion is something like:

```
git spr update --upto 2
```

with the UI borrowed from `git spr merge`. We'd also want to make sure it doesn't prune the existing PR3 and PR4 :smile:

**Comment by ejoffe** [comment]
+1 - cool feature. 
I never had this use case personally, I just don't commit my changes to PR3 and PR4 until they are ready, but maybe if I had this flag I would.
