### ISSUE TITLE
Does this work with private repo?

### ISSUE THREAD

**Issue by Huxpro** [ejoffe/spr#213]
Hey, thanks for building this. I went for a try but seems to get no luck:

```
λ git spr u
> git rev-parse --show-toplevel
> git fetch
> git rebase origin/main --autostash
> github fetch pull requests
> git branch
> git log origin/main..HEAD
> git status --porcelain --untracked-files=no
> github fetch pull requests
> git branch
pull request stack is empty
```

So i'm wondering is it because i'm working with a private repo? I guess this script works by querying Github API?

**Comment by ejoffe** [comment]
From your log it looks like your setup is all good, you just don't have any new commits. 
You should be able to make a commit, call `git spr u` and the pr should be created.

**Comment by Huxpro** [comment]
Thanks everyone! 

@ejoffe Emm...I actually had 4 more commits ahead of `origin/main`. `git log origin/main..HEAD` shows them as well. Do you know what could go wrong and how can I triage? 

They are in a different branch. 

I even tried 
- rebasing them to `main` and `git spr u` 
- checkout toe the 1st commit and `git spr u`
but still got `pull request stack is empty`

**Comment by ejoffe** [comment]
As long as you are calling git spr u in the branch that has the commits, it should work. 
In general you can work in whatever branch you want, or work in multiple branches, each branch creates its own stack of commits/prs. The behavior you are experiencing is very odd. 
You can try to run it with debug and see if it sheds any light:
`git spr --debug --verbose update`

**Comment by Huxpro** [comment]
@ejoffe Thanks! Here is what I got

```
repo_name git/branch_name  64s
λ git spr --debug --verbose update
> git rev-parse --show-toplevel
Config : {
  "Repo": {
    "GitHubRepoOwner": "",  // omitted
    "GitHubRepoName": "repo_name",
    "GitHubHost": "github.com",
    "RequireChecks": true,
    "RequireApproval": true,
    "GitHubRemote": "origin",
    "GitHubBranch": "main",
    "MergeMethod": "rebase"
  },
  "User": {
    "ShowPRLink": true,
    "LogGitCommands": true,
    "LogGitHubCalls": true,
    "StatusBitsHeader": true,
    "StatusBitsEmojis": true,
    "CreateDraftPRs": false,
    "Stargazer": false,
    "RunCount": 24
  }
}
3:00PM DBG ../../../runner/work/spr/spr/git/realgit/realcmd.go:45 > git fetch
> git fetch
3:00PM DBG ../../../runner/work/spr/spr/git/realgit/realcmd.go:45 > git rebase origin/main --autostash
> git rebase origin/main --autostash
> github fetch pull requests
3:00PM DBG ../../../runner/work/spr/spr/git/realgit/realcmd.go:45 > git branch
> git branch
3:00PM DBG ../../../runner/work/spr/spr/github/githubclient/client.go:273 > GetInfo Info={"LocalBranch":"\u001b[1;32mbranch_name\u001b[m","PullRequests":null,"RepositoryID":"R_kgDOGziB_g","UserName":"Huxpro"}
3:00PM DBG ../../../runner/work/spr/spr/git/realgit/realcmd.go:45 > git log origin/main..HEAD
> git log origin/main..HEAD
3:00PM DBG ../../../runner/work/spr/spr/git/realgit/realcmd.go:45 > git status --porcelain --untracked-files=no
> git status --porcelain --untracked-files=no
> github fetch pull requests
3:00PM DBG ../../../runner/work/spr/spr/git/realgit/realcmd.go:45 > git branch
> git branch
3:00PM DBG ../../../runner/work/spr/spr/github/githubclient/client.go:273 > GetInfo Info={"LocalBranch":"\u001b[1;32mbranch_name\u001b[m","PullRequests":null,"RepositoryID":"R_kgDOGziB_g","UserName":"Huxpro"}
pull request stack is empty
```

But my `git lg` be like

```
* 10a1700 - (HEAD -> branchname) ...
* 8879720 - ...
* 7d26df0 - ...
* 928f83f - ...
* 8d52a85 - (origin/main, main) ...
```

**Comment by ejoffe** [comment]
Unfortunately that doesn't add too much color. 
It looks like an issue with parseLocalCommitStack function, I am guessing that for some reason it's returning an empty list of commits. 
This function goes through the output of `git log origin/main..HEAD` and mainly looks for the following two regexes to parse the output:
```
	commitHashRegex := regexp.MustCompile(`^commit ([a-f0-9]{40})`)
	commitIDRegex := regexp.MustCompile(`commit-id\:([a-f0-9]{8})`)
```
can you check or paste a sanitized version of the output of `git log origin/main..HEAD`?

**Comment by Huxpro** [comment]
@ejoffe thanks for the prompt response!

```
repo_name git/main*  13s
commit 10a17001e7b11484ed4610db6f0c1e405ed19c9e (HEAD -> branch_name)
Author: Xuan Huang <a@b.com>
Date:   Wed Mar 9 17:32:08 2022 -0800

    [Blah] Blah


commit 887972046e17485d3559c6b666329c2a7c5c5671
Author: Xuan Huang <a@b.com>
Date:   Wed Mar 9 16:48:48 2022 -0800

    [Foo] Bar

commit 7d26df0bced0efff96bd57470c1a187afa9248bf
Author: Xuan Huang <a@b.com>
Date:   Wed Mar 9 15:11:20 2022 -0800

    [Wola] Hey


commit 928f83faaad4d4fa79d0592c4641556f4a66a676
Author: Xuan Huang <a@b.com>
Date:   Tue Mar 8 22:00:10 2022 -0800

    [Tag] Title
```

**Comment by ejoffe** [comment]
I'll add some more debug logs to the next version of spr, and hopefully we can get more insight into what's going on. 
If you are comfortable with go, feel free to debug and try to root cause this yourself as well. Bug fixes are always more than welcome.

**Comment by ejoffe** [comment]
@Huxpro - I added some more debug logs in v0.8.3. You can try to run with -debug flag and see if we can get more insights into what's going on.

**Comment by Huxpro** [comment]
Hey @ejoffe, I just upgraded to v0.8.3 and tested it out. But you know what, this times it just works™️! The shame is that we don't know what was happened but I think we can close this for now.

It took me a while to get back to you since I was in the middle of a stack using <https://github.com/ezyang/ghstack> and I'm pretty sure using both would blow my stack up hah. I'm going to give spr a try before settling down on either spr or ghstack, but I'm curious how do you compare spr vs. ghstack? At a high-level they seems to be really close: stacked commits -> stacked PR; nice PR message on Github; Needs special command for merging, etc. 

I do see https://github.com/ejoffe/spr/issues/115 (`git error: There is no tracking information for the current branch.`) when I was trying to `git amend` though. It seems like it generates a `fixup!` commit rather than `git commit --amend` (does this work?)?

**Comment by Huxpro** [comment]
Actually, `git spr merge` doesn't do anything because the stack check failed

```
 ┌─ github checks pass
 │ ┌── pull request approved
 │ │ ┌─── no merge conflicts
 │ │ │ ┌──── stack check
 │ │ │ │
[✅❌✅❌] 
[✅❌✅❌] 
```

I'm not sure what happened? That's the only two PRs out there and Github shows them "rebase and merge"-able as well.

**Comment by Huxpro** [comment]
Ok it seems like `git error: There is no tracking information for the current branch.` is caused by the local branch doesn't have an origin upstream. So rebasing on `main` (which is tracking `origin/main`) then `git amend` works fine (although it fired up another stack of PR, Oops)

But the stack check still failed and `git spr merge` still does nothing...emm

**Comment by ejoffe** [comment]
Glad it's working!

I haven't used ghstack, so I'm not the best person to compare. I'd love to know though, so if you use both, I would be interested to know the differences. 

Looks like your pr hasn't be approved, you either need someone to approve the pr on the github review ui, or you can disable pr approval in your repository .spr.yml, set requireApproval to false. 

The amend bug #115 should be fixed in v0.8.4, if you get the latest you'll have the fix.

**Comment by Huxpro** [comment]
@ejoffe Oh wasn't know the stack check flag is correlated to the approval flag. Yea it merged just fine! Thanks for the supports!

> I haven't used ghstack, so I'm not the best person to compare. I'd love to know though, so if you use both, I would be interested to know the differences.

I'll use `spr` for a while and let you know. My first impression is that the CLI TUI feels more friendly!

**Comment by dansimau** [comment]
I am also getting the same issue, version 0.14.4.

```
$ git spr --verbose --debug up --detail
> git rev-parse --show-toplevel
Config : {
  "Repo": {
    "GitHubRepoOwner": "<redacted>",
    "GitHubRepoName": "<redacted>",
    "GitHubHost": "github.com",
    "GitHubRemote": "origin",
    "GitHubBranch": "develop",
    "RequireChecks": true,
    "RequireApproval": true,
    "MergeMethod": "rebase",
    "MergeQueue": true,
    "PRTemplatePath": "",
    "PRTemplateInsertStart": "",
    "PRTemplateInsertEnd": "",
    "MergeCheck": "",
    "ForceFetchTags": false
  },
  "User": {
    "ShowPRLink": true,
    "LogGitCommands": true,
    "LogGitHubCalls": true,
    "StatusBitsHeader": true,
    "StatusBitsEmojis": true,
    "CreateDraftPRs": true,
    "PreserveTitleAndBody": false,
    "NoRebase": false
  },
  "State": {
    "MergeCheckCommit": {},
    "Stargazer": false,
    "RunCount": 29
  }
}
5:14PM DBG ../../../Users/runner/work/spr/spr/git/realgit/realcmd.go:58 > git fetch
> git fetch
5:14PM DBG ../../../Users/runner/work/spr/spr/git/realgit/realcmd.go:58 > git rebase origin/develop --autostash
> git rebase origin/develop --autostash
> github fetch pull requests
5:14PM DBG ../../../Users/runner/work/spr/spr/git/realgit/realcmd.go:58 > git log --format=medium --no-color origin/develop..HEAD
> git log --format=medium --no-color origin/develop..HEAD
5:14PM DBG ../../../Users/runner/work/spr/spr/git/helpers.go:100 > parseLocalCommitStack lines=11
5:14PM DBG ../../../Users/runner/work/spr/spr/git/helpers.go:155 > parseLocalCommitStack commits=null
5:14PM DBG ../../../Users/runner/work/spr/spr/git/realgit/realcmd.go:58 > git branch --no-color
> git branch --no-color
5:14PM DBG ../../../Users/runner/work/spr/spr/github/githubclient/client.go:204 > GetInfo Info={"LocalBranch":"daniel.simmons/<redacted>","PullRequests":[],"RepositoryID":"<redacted>","UserName":"dansimau"}
5:14PM DBG ../../../Users/runner/work/spr/spr/git/realgit/realcmd.go:58 > git log --format=medium --no-color origin/develop..HEAD
> git log --format=medium --no-color origin/develop..HEAD
5:14PM DBG ../../../Users/runner/work/spr/spr/git/helpers.go:100 > parseLocalCommitStack lines=11
5:14PM DBG ../../../Users/runner/work/spr/spr/git/helpers.go:155 > parseLocalCommitStack commits=null
5:14PM DBG ../../../Users/runner/work/spr/spr/git/realgit/realcmd.go:58 > git status --porcelain --untracked-files=no
> git status --porcelain --untracked-files=no
> github fetch pull requests
5:14PM DBG ../../../Users/runner/work/spr/spr/git/realgit/realcmd.go:58 > git log --format=medium --no-color origin/develop..HEAD
> git log --format=medium --no-color origin/develop..HEAD
5:14PM DBG ../../../Users/runner/work/spr/spr/git/helpers.go:100 > parseLocalCommitStack lines=11
5:14PM DBG ../../../Users/runner/work/spr/spr/git/helpers.go:155 > parseLocalCommitStack commits=null
5:14PM DBG ../../../Users/runner/work/spr/spr/git/realgit/realcmd.go:58 > git branch --no-color
> git branch --no-color
5:14PM DBG ../../../Users/runner/work/spr/spr/github/githubclient/client.go:204 > GetInfo Info={"LocalBranch":"daniel.simmons/<redacted>","PullRequests":[],"RepositoryID":"<redacted>","UserName":"dansimau"}
pull request stack is empty
```

Running `git log` manually shows my commit:

```
$ git log --format=medium --no-color origin/develop..HEAD
commit 44ffc995 (HEAD -> daniel.simmons/<redacted>)
Author: Daniel Simmons <dan.simmons@<redacted>>
Date:   Fri Nov 24 17:13:00 2023 +0100

    <redacted>

commit 97e609a1
Author: Daniel Simmons <dan.simmons@<redacted>>
Date:   Fri Nov 24 15:57:42 2023 +0100

    <redacted>
```

Will try to debug more later, but it looks like commit parsing is failing.

```
$ git version
git version 2.42.0
```

**Comment by dansimau** [comment]
Okay issue here is that I have this in my `~/.gitconfig`:

```
[log]
abbrevCommit=true
```

And thus it doesn't match the regexp. I'll file a separate issue.
