### ISSUE TITLE
Bug? `git amend` leaves `fixup!` commit

### ISSUE THREAD

**Issue by yogurtearl** [ejoffe/spr#222]
When using `git amend` it seems to be leaving a `fixup!` commit even after the `git rebase -i --autosquash --autostash` is successful. 

I have to do `git rebase -i --autosquash main` after `git amend` to get it to squash in the fixup commit. It seems to need the `main` branch in the rebase command.

git: 2.35.1
spr: 0.8.3

**Comment by ejoffe** [comment]
I guess this is the beginning of the troubles you had and potentially causing #224.
Is it correct to do the following:
`git rebase -i --autosquash --autostash origin/main`

**Comment by yogurtearl** [comment]
> Just to make sure, the issue here is that the rebase command is missing the upstream?

yup. it just does `git rebase -i --autosquash --autostash` (missing the `origin/main`), which fails to squash the fixups.

my `.spr.yml` in the repo has: 
```
githubRemote: origin
githubBranch: main
```

**Comment by jameskyle** [comment]
Seeing this too.
