### ISSUE TITLE
Bug? `spr` merges 2nd PR in the stack before the first. 

### ISSUE THREAD

**Issue by yogurtearl** [ejoffe/spr#227]
(different stack and repo from https://github.com/ejoffe/spr/issues/224) 

I had 4 PRs in the stack, the bottom 2 were mergable. 
Everything looked in order, as expected. 

**Actual**
I did `git spr merge` and it tried to merge the second PR before the bottom PR. 🤔 

**Expected**
`git spr merge` completes the merge of the bottom PR before even attempting to merge the next PR up in the stack.

**Comment by ejoffe** [comment]
`git spr merge` actually combines all your mergeable prs into one (the top mergable pr on the stack), then it merges that one and closes the rest of the pull requests underneath. see issue #209 for more info.

**Comment by yogurtearl** [comment]
ah, ok, that was not clear to me from the README https://github.com/ejoffe/spr#merging-pull-requests
you can close this or re-purpose it as a "clarify how merge works in the readme" ticket. :) 

#209 was the behavior I expected. 

I guess you could call `git spr merge --upto 1` repeatably to simulate that behaviour?

**Comment by ejoffe** [comment]
Yes, If you really want to merge everything one by one, you can do `git spr merge --upto X` where X is the number of the bottom pr.
