### ISSUE TITLE
FR: yml for "only merge one at a time"

### ISSUE THREAD

**Issue by dhalperi** [ejoffe/spr#231]
Basically, I'd like my default to be always `--upto <bottom of stack>`. Would be nice if this was available as an option in yml, as actually generating that command takes work.

Would be happy to work on/send a PR if that is something you'd be interested in.

**Comment by ejoffe** [comment]
how about a flag that does this:
```
git spr merge --count 1
git spr merge -c 1
```

**Comment by dhalperi** [comment]
What would also be great.

**Comment by ejoffe** [comment]
I'm ok with either or both, I personally prefer the flag approach for this case. 
Pull request more than welcome!
