### ISSUE TITLE
Adding tags around links is unnecessary and messes up GitHub formatting

### ISSUE THREAD

**Issue by CyanoKobalamyne** [ejoffe/spr#237]
GitHub automatically linkifies strings that look like links. However, `spr` currently adds explicit `<a>` tags around links, which messes up the formatting for e.g. Markdown links like [this](http://www.example.com) that are in a list.

**Comment by leoluk** [comment]
This exists because we used to put the commit message into a code area to preserve formatting, requiring separate linkify.

Looks like the code area was removed but the linkify is still there. We can just remove that too now...
