### ISSUE TITLE
Amending commits in the middle of a stack

### ISSUE THREAD

**Issue by matan-starkware** [ejoffe/spr#254]
I have a question for changing commits that already have associated PRs. Imagine the following stack:
- HEAD, commit2 - changes overlap w changes from commit1
- commit1
- origin

The [example in the README](https://github.com/ejoffe/spr#amending-commits) seems to show that I make changes from HEAD, and can then apply them to an earlier commit. The problem is that the state in HEAD conflicts with commit1. So to update commit1 properly I need to check it out, update it, and then rebase commit 2 back on top. How can I do something like this?

**Comment by ejoffe** [comment]
Great question Matan. 
Amending an earlier commit using 'git amend' under the hood just uses a fixup commit and rebase. 
In case of conflicts, you'll just have to fix the conflict in your commit1, rebase --continue, and then fix the conflict in commit2. This will basically be the same as checking it out and updating and rebasing it. 

IMO one of the trickier part of working with stacks of commits is the interactions between the commits, especially as the stack grows large. This is just something you get used to in this workflow. I personally try to avoid self conflicts, sometimes I combine commits, other times I'll add a third commit on top to avoid the conflict, more rarely I go the path of amending a conflict and fixing it.

**Comment by matan-starkware** [comment]
Thanks for the response Eitan, I really like the tool.

Glad to hear this still works even if merge conflicts occur. What about if the code in the commit I want to update doesn't exist at HEAD? Imagine that in commit1 I had:

```
def f():
    bad_var_name = ...  # reviewer asks that I improve the variable name.
    # partial functionality.
```

commit10 then comes along and changes the functionality significantly enough that `bad_var_name` gets removed from the function. How could I follow my reviewer's request on commit1 to use a better variable name if it doesn't exist at HEAD?

**Comment by ejoffe** [comment]
Tell your reviewer this is no longer an issue as the variable has been removed in a follow on commit. 
The real answer is that each of these situations has a solution, and your job is to find the one that best fits the situation.

**Comment by matan-starkware** [comment]
Hi Eitan, so I've continued playing around and `git spr` has worked fine with the flow that I wanted. I've been able to do:

```
git checkout <commit in middle of stack>
# Make changes
git add . && git commit --amend
git rebase -i HEAD <branch name>
git spr update
```

AFAICT it has always managed to re-map the rebased commits to the correct PR and I've managed to merge a PR chain after doing this without issue. This tool is great :)

I think the ability to actually make changes while checked out at the commit you want to change is really powerful and maybe it's worth checking if you think this is stable enough to add to the documentation?

**Comment by ejoffe** [comment]
@matan-starkware - I'll add it to the doc as an alternative method to the 'git amend' approach. 
Also git spr handles reordering of commits in the stack and re-stacks your prs correctly, so if you have a commit at the top that is ready to merge, but something in the middle that isn't. You can reorder the commit using rebase -i, call spr update, and you are good to go.

**Comment by leoluk** [comment]
The problem with the "git checkout" approach is you end up with an inconsistent local stack - not sure if we should recommend it for new users, could be confusing. Unlike a "git rebase -i" of the full stack, it won't rebase the "upper" commits.
