### ISSUE TITLE
Commits show up as "unverified" when using `git spr update` after amending commits.

### ISSUE THREAD

**Issue by mahmoudimus** [ejoffe/spr#255]
compare:

- <img width="197" alt="image" src="https://user-images.githubusercontent.com/40820/175955318-f63f0273-9691-4019-9c78-ed58199b1e25.png">

with:

- <img width="754" alt="image" src="https://user-images.githubusercontent.com/40820/175955590-db463e2e-4e78-4839-a6fb-d9855f8b3656.png">

Would love any guidance on how to debug/assist/fix?

**Comment by ejoffe** [comment]
Closing stale issue
