### ISSUE TITLE
Broken version (?)

### ISSUE THREAD

**Issue by Itay-Tsabary-Starkware** [ejoffe/spr#257]
Hi,

Thanks for creating this tool, super useful!

I am running into an unexpected problem with the `version` flag:

```
git spr --debug version
> git rev-parse --show-toplevel
Config : {
  "Repo": {
    "GitHubRepoOwner": <redacted>,
    "GitHubRepoName": <redacted>,
    "GitHubHost": "github.com",
    "RequireChecks": true,
    "RequireApproval": true,
    "GitHubRemote": <redacted>,
    "GitHubBranch": <redacted>,
    "MergeMethod": "merge"
  },
  "User": {
    "ShowPRLink": true,
    "LogGitCommands": true,
    "LogGitHubCalls": true,
    "StatusBitsHeader": true,
    "StatusBitsEmojis": true,
    "CreateDraftPRs": false,
    "PreserveTitleAndBody": false,
    "Stargazer": false,
    "RunCount": 47
  }
}
dev : unknown : dversion
```

I installed [from source](https://github.com/ejoffe/spr#from-source) on July 21 (i.e., a week ago).

Thanks!

**Comment by ejoffe** [comment]
Hi Itai, 
The version is currently set by the build tool (go releaser) through link flags.
I think if you build it yourself from source you won't get these. 
If you have goreleaser installed, you can try `make bin` and I think you should get a valid version.
