### ISSUE TITLE
Don't include commit-id if not creating stacked commits

### ISSUE THREAD

**Issue by danielcompton** [ejoffe/spr#267]
Many of my commits are not using spr. However, they still get commit-id appended to the commit message.

Ideally I'd be able to not have any commit-ids in my commit messages until I created a stacked pull request. Then spr would go through the commits about to be converted into PRs and assign a commit-id then.

**Comment by ejoffe** [comment]
@danielcompton - I really have to thank you!
At first I dismissed this idea as not a big deal, but the whole commit-msg hook was always annoying me. 
The need to install a hook into the .git/hooks dir always left a bad taste for me, but I couldn't think of another way. 
This issue has caused me to rethink the whole message hook and instead now spr will just use a magical rebase to add the commit-ids while updating the prs. This solves your issue of having commit-ids in commits that aren't using spr, but also removes the whole need for the commit hook.
Thank you!
