### ISSUE TITLE
What's the difference with getcord's spr

### ISSUE THREAD

**Issue by dko-slapdash** [ejoffe/spr#275]
Hi.

What's the story behind having the tool with the similar purpose and same name, but written in Rust?
https://github.com/getcord/spr/

That repo doesn't mention you, and also you don't mention them anywhere.

P.S.
BTW IMHO your killer feature and a huge competitive advantage is that super-nice block which references other commits in the stack which the tool auto-adds to every PR description. It's super-cool. After I saw it, I feel the real pain in missing it in other tools. (Unfortunately, you do not update this block there if `preserveTitleAndBody:true` is set in ~/.spr.yml - which is such a pity.)

**Comment by ejoffe** [comment]
I haven't tried getcord, so I don't know the actual difference. 
From the docs it looks like a very similar solution to the pull request stacking issues GitHub has. 
I'll add an enhancement request to have the stack output remain even when preserveTitleAndBody is used, if someone feels inspired they can implement it. 
Personally, I don't see it as a competition, if getcord works better for you, I'm glad there are more options out there. I keep my competition to my actual business http://www.inigo.io (if you are using GraphQL, you should check it out). 
Would be cool to have a comparison of getcord and spr, feel free to use this feature for that if you want.
