### ISSUE TITLE
bug: incorrect stack order in PR

### ISSUE THREAD

**Issue by jgarside-hrp** [ejoffe/spr#277]
`v0.9.2`

When adding a commit to the beginning of the stack it shows up in the correct order in the CLI, but not in the PR description update (`add tmp2 file` is the beginning of the stack but was created later).

![image](https://user-images.githubusercontent.com/108759135/193732641-6f1d7137-5890-4776-94d9-65614849cb8f.png)

**Comment by jgarside-hrp** [comment]
Interestingly it worked on the 2nd `git spr update` after I added a 4th commit to the end.

**Comment by ejoffe** [comment]
thank you for reporting, looks like the pr stack description doesn't handle reordering of commits correctly.
