### ISSUE TITLE
Support for repos that have 'Require a pull request before merging' + 'Require approvals' enabled

### ISSUE THREAD

**Issue by dan-v** [ejoffe/spr#284]
While I was testing out spr, I realized that it does not play nicely with repos that have the setting `Require a pull request before merging` + `Require approvals` enabled on the main/master branch. On merge, it changes the base branch for the top of stack PR which causes existing approvals to be set to stale, which causes the merge to fail as there are no approvals on that PR anymore. I looked through the Github repo settings to see if there was any way to make PR reviews not become stale on base branch change, but I didn't see anything unfortunately. I'm mostly wondering if there is any way spr could still be used with repos that have these setting enabled. If there is, I'd be happy to contribute a change.

<img width="782" alt="Screenshot 2023-02-01 at 9 52 40 AM" src="https://user-images.githubusercontent.com/1596016/216123447-510243a5-3e53-4c2c-ad6c-8a2109c54ee4.png">

**Comment by ejoffe** [comment]
Hi Dan, 

Unfortunately it's not possible to set require pull requests on the stacked prs. 
At Inigo we are using the following setup which works quite well for us, so hopefully it will work for you as well.
We have the following rules set on the base `master` branch:

<img width="779" alt="Screenshot 2023-02-01 at 10 11 44 AM" src="https://user-images.githubusercontent.com/1152760/216127583-a5429c94-bc05-4677-9886-d896142adb5b.png">

Then setup another branch rule:
`pr/*/*/*`
And use the following setup:
![Uploading Screenshot 2023-02-01 at 10.14.34 AM.png…]()
Also "allow forced pushes" on these branches. 

Lastly, in your .spr.yml:
```
requireChecks: true
requireApproval: true
```

With this setup, although pull request approval isn't "required" in github, spr still checks that the commit/branch has a pr approval, and you can see the status of your stack using `git spr status`.

Hope that helps. 
Eitan

**Comment by dan-v** [comment]
This is super helpful! Thank you so much @ejoffe
