### ISSUE TITLE
Does SPR play nice with the new merge queue features?

### ISSUE THREAD

**Issue by jameskyle** [ejoffe/spr#289]
Topic says it all. I'm curious if spr plays nice with merge queues. We've enabled these in our org, so I could find out soon enough (and will update). But curious if anyone's investigated yet?

https://github.blog/changelog/2021-10-27-pull-request-merge-queue-limited-beta/

**Comment by ejoffe** [comment]
I would be interested to know as well if someone tries this out.

**Comment by jameskyle** [comment]
Testing now, it doesn't seem to work. I get the following error

```
FTL ../../../runner/work/spr/spr/github/githubclient/client.go:468 > pull request merge failed error="Something went wrong while executing your query. Please include `CE75:757B:1E3601A:1F287C2:64139CDC` when reporting this issue.\n" id=PR_kwDOBV0xv85MJxhB number=6270 title="My Commit Title #ci"
```

**Comment by jameskyle** [comment]
@ejoffe are there any plans to support this? I'm guessing it's going to be tricky.

**Comment by ejoffe** [comment]
I don't think it should be too tricky, but I don't currently have a use case for merge queues, so I can't test it. 
I think to get this to work, instead of calling the merge api on the pull request, the code needs to be updated to call an api which sends this pr to the merge queue. The change itself to spr shouldn't be hard, but one would have to figure out the new api (I haven't looked to see if there is even an api for this from github).

**Comment by jameskyle** [comment]
Now that I look....it's not obvious that the behavior is exposed through the API yet. I'm asking our platform team who set it up.

**Comment by jameskyle** [comment]
Ok, not available through the REST API, but [it is in the GraphQL API](https://stackoverflow.com/questions/69916356/how-do-i-enable-auto-merge-on-a-github-pull-request-via-the-rest-api).

**Comment by jameskyle** [comment]
I'm already setup to build spr from when I was troubleshooting a bug (now fixed) a while back.

**Comment by jameskyle** [comment]
Ok, built off of an updated main. Tested in a test repository

* goreleaser was dodgey. Kept locking up, did not debug too much...just built the bins directly with go build
* Created a 3 PR stack
* Had a coworker approve the PR at the top of the stack, but not the next two.

Config:

```yaml
githubRepoOwner: SafeGraphInc
githubRepoName: dev-testing-repository
githubHost: github.com
requireChecks: true
requireApproval: true
githubRemote: origin
githubBranch: main
remoteBranches: []
mergeMethod: squash
```

Status of pr looks like

<img width="759" alt="image" src="https://user-images.githubusercontent.com/8234/233741473-ef2312e7-4851-4d62-962c-71aaad0308c0.png">

`git merge --count 1` returns

```
❯ git spr merge --count 1
> git rev-parse --show-toplevel
> github fetch pull requests
> git branch --no-color
> git branch --no-color
```

I noted that the "passed checks" gate is shown as not cleared. Not sure if this is a bug with the current changes or, maybe, a  bug if that flag is set but there are no custom checks set other than approval. So I disabled this flag producing a status of

<img width="721" alt="image" src="https://user-images.githubusercontent.com/8234/233741674-acdb4b53-c1d6-4602-9eda-25d55d118b8b.png">

I then executed the merge command again

```
> git rev-parse --show-toplevel
> github fetch pull requests
> git branch --no-color
> git branch --no-color
> github update 1 : First stack
> git branch --no-color
> github merge 1 : First stack
MERGED https://github.com/SafeGraphInc/dev-testing-repository/pull/1 : First stack
```

Success! Verified on the PR that it's been merged. I won't be able to know if it works when there's a delay in the queue till I test on our main repository that has a lengthy CI gate.

However, with the exception of the checks requirement blocking even though there were no checks....looks like a good start!

**Comment by ejoffe** [comment]
I have gone a head and merged the pull request, it's in v0.12.1.
Let see how it handles when there is delay in the merge queue, feel free to open a new issue if more details are needed.

**Comment by jameskyle** [comment]
@ejoffe Sure thing, also note the issue with the github checks. But I'm not sure if this is particular to the merge queue changes or maybe a general issue.

**Comment by jameskyle** [comment]
And thanks!
