### ISSUE TITLE
Git spr is not reporting the branch names in the Github PR that it would do earlier.

### ISSUE THREAD

**Issue by MayureshGharat** [ejoffe/spr#337]
Earlier:
![Screenshot 2023-06-21 at 12 00 11 PM](https://github.com/ejoffe/spr/assets/4326831/70596130-d806-4cd4-ba1a-052440fdbea6)

Now after spr update to latest:
![Screenshot 2023-06-21 at 11 59 55 AM](https://github.com/ejoffe/spr/assets/4326831/e2fa72f2-e389-40cb-913f-0683c1a3d6f6)

I also see a message on `git spr u`:

```
⚡  git spr u
error: unable to fetch remote branch info, using defaults> git rev-parse --show-toplevel
> git fetch
> git rebase origin/main --autostash
```

Can you advice?

**Comment by ejoffe** [comment]
The naming pr branches has changed in the latest version.
Old version used to be: pr/<user_name>/<local_branch>/<commit-id>
New approach: spr/<remote_branch>/<commit-id>

This does mean that migrating from 12 -> 13, new prs will be created and the old ones need to be manually closed.
Hope this helps.

**Comment by MayureshGharat** [comment]
@ejoffe thanks a lot for quick reply.
How can we know branch names. The main reason I ask is we can have a person working on multiple branches at the same time and would be waiting for the reviews. Once a PR for a particular branch is shipped, the person might want to go to that branch to commit the PR using: `git spr merge -c 1`.
Earlier, I could look at the local branch name like `TemporalFixes` in the above screenshot and navigate to that branch and commit my PRs.

**Comment by ejoffe** [comment]
Unfortunately this is no longer possible. The person will now have to know which pr belongs to which branch.
The reason for this change is to make it easier and possible to share prs across users and branches. 
Personally in our workflows we end up using very little branches. 95% of the time everyone works on a single branch, just keep stacking and merging. There are some exceptions where a new branch is created, but those are usually very short lived.

**Comment by MayureshGharat** [comment]
I see. I was able to workaround a bit and get hold of the branch. Little painful but not a blocker.
![image](https://github.com/ejoffe/spr/assets/4326831/595b0468-a017-4c7e-bafb-73775f3dbe8e)
and then
<img width="1130" alt="Screenshot 2023-06-21 at 1 08 19 PM" src="https://github.com/ejoffe/spr/assets/4326831/fe1ee916-d2f6-445a-bd1c-b96eb67a8cc9">

**Comment by ejoffe** [comment]
One idea you might be able to try is to write a github bot (or maybe there is one out there) that labels the prs with the local branch.
