### ISSUE TITLE
Formula Name Conflict Between Two Projects

### ISSUE THREAD

**Issue by kud** [ejoffe/spr#352]
Hello maintainers,

I wanted to bring to your attention that there's a naming conflict for the formula between these two projects:

- [getcord/spr](https://github.com/getcord/spr)
- [ejoffe/spr](https://github.com/ejoffe/spr)

I use both of these projects and have experienced conflicts when attempting to install them together. I understand that naming can be tricky, but it would be greatly appreciated if one of the projects could consider renaming their formula to avoid this issue. This would greatly enhance the user experience for those of us utilizing both tools.

![image](https://github.com/ejoffe/spr/assets/655838/23913b87-2503-4cb6-b846-bc473f47cbc9)

Thank you for your understanding and consideration. I really appreciate the hard work you've put into developing these tools.

Best regards,

Related: https://github.com/getcord/spr/issues/177

**Comment by ejoffe** [comment]
This is indeed very unfortunate. 
In fact, it used to be that `brew install spr` would just work for installing this package, but then getcord overwrote it and hence you now need to use the full path for this package with `brew install ejoffe/tap/spr`. 
As the older repo and tool, I have no plans to change the name of the tool or the tap at this point of time.

**Comment by maverick1872** [comment]
@ejoffe while I agree with your perspective; [getcord/spr](https://github.com/getcord/spr) has been introduced into the [core homebrew repository](https://github.com/Homebrew/homebrew-core/commit/5188653a0ea0a48a1c856e000106932e769264db) as such the onus likely falls to you unfortunately.

**Comment by ejoffe** [comment]
no current plans to rename the tool. closing this issue.

**Comment by davinkevin** [comment]
FYI: https://github.com/orgs/Homebrew/discussions/4782#discussioncomment-10115587
