### ISSUE TITLE
Default config files not written

### ISSUE THREAD

**Issue by piefel** [ejoffe/spr#372]
The README states:

> When the script is run for the first time two config files are created. Repository configuration is saved to .spr.yml in the repository base directory.

That is not what I observe. The files are not written, at least not on `git spr status`, and the warning messages from rake about the missing files are always repeated.

I don’t know what the preferred behaviour should be. The warnings are a bit irritating, so fixing this seems in order. Alternatively, document the real behaviour in the README.

**Comment by ejoffe** [comment]
There was a recent update which removed the writing / updating of configuration files. 
However, I believe the correct approach is to create the file if it doesn't exist as an init step, but not overwrite it there after.
