### ISSUE TITLE
How do I start a new stack?

### ISSUE THREAD

**Issue by jonathanloske** [ejoffe/spr#377]
How do I start a new stack? Or do I have a wrong mental model and I shouldn't start a new stack?

Background: I just finished working on a feature and picked up a bug as a next task. The bug fix should not be dependent upon the stack for the feature I worked on and should be mergable independent of how far the feature is along.

PS: Loving Git SPR so far, thanks a lot! ❤️

**Comment by ejoffe** [comment]
You can work in multiple stacks, just start a new git branch. Each branch is like it's own stack. 
You can even work on stacks destined to different origin branches. In our case we have release branches, and by setting the upstream of the local branch, you can have one stack point to one release branch and another stack to a different branch.

**Comment by jonathanloske** [comment]
Thanks, that helps! I feel like it would be useful to include this in the README somewhere, WDYT? I could volunteer to write a section on it 😊

**Comment by ejoffe** [comment]
Sounds great! Got for it.
