### ISSUE TITLE
Error when running from a freshly added directory

### ISSUE THREAD

**Issue by sbienkow-ninja** [ejoffe/spr#48]
I suspect this is caused when running from a freshly-added directory and SPR tries to rebase the branch.
```
git spr -u
panic: exit status 128

goroutine 1 [running]:
github.com/ejoffe/spr/spr.check(...)
	/Users/eitan/Code/spr/spr/spr.go:908
github.com/ejoffe/spr/spr.mustgit(...)
	/Users/eitan/Code/spr/spr/spr.go:754
github.com/ejoffe/spr/spr.(*stackediff).getLocalCommitStack(0xc0001b2180, 0xc0002d5af0, 0x40de58, 0x48)
	/Users/eitan/Code/spr/spr/spr.go:418 +0xc5
github.com/ejoffe/spr/spr.(*stackediff).syncCommitStackToGitHub(0xc0001b2180, 0x7d7a90, 0xc00001a180, 0xc0002f6960, 0x0, 0x0, 0x0)
	/Users/eitan/Code/spr/spr/spr.go:632 +0x85
github.com/ejoffe/spr/spr.(*stackediff).UpdatePullRequests(0xc0001b2180, 0x7d7a90, 0xc00001a180)
	/Users/eitan/Code/spr/spr/spr.go:97 +0x10a
main.main()
	/Users/eitan/Code/spr/cmd/spr/main.go:92 +0x7d6
```
Version:
```
git spr --version
spr version : 0.4.4 : 2021-06-10T18:17:56Z : da3a051c
```

**Comment by ejoffe** [comment]
Looks like the command that failed is `git log origin/master..HEAD`. 
There is actually a separate bug right now that doesn't show the git error when a command fails. 
What do you mean by freshly-added directory? Is this a new repository?
Can you run the command locally to see the error why it fails?

**Comment by sbienkow-ninja** [comment]
I meant my PR added new directory, and `git spr -u`  does a rebase, so temporarily the directory is removed from existence.
Because if this, it's not in a git repository or any directory (`pwd` command should fail too).

But I believe that all `git` commands are executed from the top level directory, unless that's only true for aliases?

When I did `cd ../../` to move my working directory to the git root and tried again, it worked just fine.

**Comment by ejoffe** [comment]
Ok, I understand. When spr pushes the separate commits to github, the new directory is removed and the git commands fail.
