### ISSUE TITLE
git error: unable to delete: remote ref does not exist

### ISSUE THREAD

**Issue by sbienkow-ninja** [ejoffe/spr#53]
This consistenly happens whenever I run `git spr -m`. The PRs are getting merged properly regardless of this error. This was happening since my first SPR, which I believe was v0.4.3. For sure happened in v0.4.4 and continues to happen in v0.5.0.
```sh
$ git spr -m
git error: error: unable to delete 'pr/sbienkow-ninja/mybranch/1e2f4484': remote ref does not exist
error: failed to push some refs to 'github.com:organisation/repo.git'
error deleting branch: exit status 1
MERGED github.com/organisation/repo/pull/392 : My First Commit
MERGED github.com/organisation/repo/pull/387 : My Second Commit
```
Sadly I didn't have new logging enabled, will do that next time I merge something.

**Comment by sbienkow-ninja** [comment]
Verbose logs:
```sh
$ git spr -m
> git rev-parse --show-toplevel
> github fetch pull requests
> git branch --show-current
> github update 388 - Update SPR to v0.5.0
> github merge 388: Update SPR to v0.5.0
> git push -d origin pr/sbienkow-ninja/mybranch/2164f418
git error: error: unable to delete 'pr/sbienkow-ninja/mybranch/2164f418': remote ref does not exist
error: failed to push some refs to 'github.com:organisation/repo.git'
error deleting branch: exit status 1
MERGED github.com/organisation/repo/pull/388 : Update SPR to v0.5.0
> github fetch pull requests
> git fetch
> git branch --show-current
> git rebase origin/master --autostash
> git log origin/master..HEAD
> git status --porcelain --untracked-files=no
> git stash
> git stash pop
> github fetch pull requests
> git branch --show-current
```
Possible GH is already set to delete the branch upon merge, and thus it doesn't exist?

**Comment by ejoffe** [comment]
Is the branch really gone? perhaps we can silently ignore this error if trying to delete a branch that's not there. 
I think the branch that got merged might get automatically removed by github, and so you see this error. 
If you have a stack of changes being merged, the closed pull requests will not get automatically removed, so I would expect this error to only happened on the top merged request.

**Comment by sbienkow-ninja** [comment]
Yes, I only get it once, always seems to be the branch with commit-id of latest commit, so I _assume_ that SPR switches that target branch of the top PR to master, merges it (which causes GH to delete it, as per repo settings) and then SPR tries to delete it too.
The "lower" PR branches are deleted without errors. So this seems very plausible.
Not sure if this setting can be detected from SPR or if it's worth just ignoring this one specific error on the top PR.
