### ISSUE TITLE
Add information about `git spr -s` output to help

### ISSUE THREAD

**Issue by GregoRCodi** [ejoffe/spr#54]
Often when looking at the output of `git spr -s` I need to go back to the readme and read https://github.com/ejoffe/spr#managing-pull-requests.

It would be great if that information about specific status checks was included in `git spr -h` (or maybe `git spr --help` for extended help, or `git spr -s -h`) :slightly_smiling_face:

**Comment by ejoffe** [comment]
How about a flag `-c --column` that adds the status bits info to the output like the following:

`[✗ - ✗ ✗] github.com/owner/repo/pull/3 : C
[✗ - ✗ ✗] github.com/owner/repo/pull/2 : B
[✗ - ✗ ✗] github.com/owner/repo/pull/1 : A
 C A C S
 h p o t
 e p n a
 c r f c
 k o l k
 s v i
   a c
   l t`

**Comment by GregoRCodi** [comment]
Technically it does the job, but I'm not sure I like the idea personally :smile: Maybe it's a matter of taste?

**Comment by ejoffe** [comment]
How about this more ascii esthetic version. 
We can add it to both the help message and as a flag, now I'm thinking `-d or --detail`

<img width="423" alt="Screen Shot 2021-06-21 at 11 12 42 AM" src="https://user-images.githubusercontent.com/1152760/122808558-e7698b00-d281-11eb-80fa-4383d6f5311a.png">

**Comment by GregoRCodi** [comment]
That one does look better IMO :+1: 

btw. won't `-d` collide with the `--debug` flag, though? Maybe we could do `-v` for verbose? I am not sure if that's actually verbose, though :smile: 

The other thing is the placement - whether to do that at the top of the bottom of the stack :thinking: Maybe both if the stack is long? Probably we could go with the bottom placement initially

**Comment by ejoffe** [comment]
Header is now on top and controlled by `--detail` flag. Is also configurable in the config file with `statusBitsHeader` configuration which defaults to true. 
There is also a new `--verbose` which enables all the logging.
