### ISSUE TITLE
Use commands instead of flags

### ISSUE THREAD

**Issue by GregoRCodi** [ejoffe/spr#55]
I was wondering if using flags (`-s`, `-m`, `-u`) was the idiomatic way of handling different actions.

It seems to me that commands (`git spr update`, `git spr merge`, `git spr status`) may be more idiomatic, as commands exclude one another by their nature (`git spr update merge` is plain wrong, just as you would not use `git diff status`), whereas flags seem like they can all be passed in at the same time `git spr -u -s -m` is as idiomatic as `git diff -a -p`)

Then, we could also provide command-specific help, e.g. only `git spr status -h` would include information from #54.

This is a minor issue, but I thought that from UNIX/CLI standpoint, commands make more sense to me in this case and I wanted to bring it up :slightly_smiling_face:

**Comment by ejoffe** [comment]
I like this idea, and I agree that sub commands would be a more idiomatic way. 
The only issue I have with this, is having to type long commands. 
I don't think git extension commands will be picked up by shell tab completions. but I haven't tested this. 
For me the most used subcommand is status, so maybe just having `git spr` as the status, and `git spr update` and `git spr merge`. At least will have less typing in the common case. 
Another potential option is to not use git-subcommand, and just have spr. After all this is really a github specific tool, and not git. In that case we would have `spr status`, `spr udpate`, `spr merge`

**Comment by GregoRCodi** [comment]
Yeah, good point. Maybe a separate CLI would make sense. I generally agree with your suggestions and don't mind which one we go for

**Comment by jmichalak-fluxninja** [comment]
Hi, if you want you can take a look at how [kubectl does it](https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/). But it has a dependency on [bash-completion](https://github.com/scop/bash-completion) and seems complicated tbh. Also it has [support for zsh](https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-zsh/). In the end, one can simply use aliases ;)

**Comment by ejoffe** [comment]
Updated spr cli to use commands instead of flags. 
The help message is better as well. Although it only works with `git spr -h`, running `git spr --help` doesn't work because git doesn't find a help page for spr and the script is never called.

**Comment by GregoRCodi** [comment]
Nice! Thanks for addressing both this and #54. Looks great :ok_hand:
