### ISSUE TITLE
Bash completion is not working

### ISSUE THREAD

**Issue by kwapik** [ejoffe/spr#67]
Even though bash completion is enabled in the `cli` [here](https://github.com/ejoffe/spr/blob/master/cmd/spr/main.go#L93) it is not working.
In the `cli` package [docs](https://github.com/urfave/cli/blob/master/docs/v2/manual.md#distribution-and-persistent-autocompletion) we can see that adding `/etc/bash_completion.d/git-spr` should help, but it didn't work as well.
It only works when invoking SPR with `git-spr`, but not by calling git subcommand `git spr`.

My request is to:
1. Add proper file to `/etc/bash_completion.d`
2. Figure out a way to work with `git spr`
3. Probably have some support for non bash shells as well

**Comment by kwapik** [comment]
Okay, I figured it out:
```bash
$ cat /etc/bash_completion.d/git-spr 
#! /bin/bash

_git_spr () {
  if [[ "${COMP_WORDS[0]}" != "source" ]]; then
    local cur opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ "$cur" == "-"* ]]; then
      opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} ${cur} --generate-bash-completion )
    else
      opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
    fi
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
  fi
}

complete -o bashdefault -o default -o nospace -F _git_spr git-spr
```

**Comment by ejoffe** [comment]
you are a true wizard 🔮
