### ISSUE TITLE
Add spr to distribution repository

### ISSUE THREAD

**Issue by jmichalak-fluxninja** [ejoffe/spr#83]
Hi, currently updating the spr is a manual process. Is there a chance for adding a package to ubuntu repository? Or providing a simple installation script?

**Comment by ejoffe** [comment]
goreleaser has a snapcraft integration (https://snapcraft.io). would that work well for you?

**Comment by jmichalak-fluxninja** [comment]
Sure, that would be cool :)

**Comment by ejoffe** [comment]
@jmichalak-fluxninja - you can now install/upgrade spr using apt! instructions in the readme.
