### ISSUE TITLE
Avoid using checkout where possible

### ISSUE THREAD

**Issue by sbienkow-ninja** [ejoffe/spr#87]
Using `git checkout` causes issues, for example when you make a few commits, then cd to a new directory and commit it too. If you were to run `git spr update`, it'll checkout first commit, leaving the shell in a non-existent directory and causing many shell hooks to scream.

It looks like most of those can be avoided - for example it appears that checkout is being done to both create/reset a branch as well as push it. These can be done without checking anything out. What is more - a local branch is not needed at all so creating it in order to delete it later can be avoided.

For example:
- Create a branch: `git branch my_new_branch <COMMIT_HASH>`
- Since you might be moving existing branch: `git branch --force my_new_branch <COMMIT_HASH>` (Seems to no longer be the case as local branches are deleted after push?)
- To push a local branch that you don't have checked out: `git push origin <LOCAL_REF>:<REMOTE_BRANCH>`. This allows pushing arbitrary refs, without the need to create local branches at all (and pollute reflog).

Referenced code which could be simplified (maybe there's more):
https://github.com/ejoffe/spr/blob/master/spr/spr.go#L402-L417
https://github.com/ejoffe/spr/blob/master/spr/spr.go#L421-L428

**Comment by ejoffe** [comment]
I didn't know you can do this. Much better now!
