### ISSUE TITLE
Allow using remotes other than origin

### ISSUE THREAD

**Issue by sbienkow-ninja** [ejoffe/spr#88]
It'd be nice to be able to override the upstream to use per-branch (extract value of https://git-scm.com/docs/git-config#Documentation/git-config.txt-branchltnamegtremote if present) as well as per-repository (for example use value from https://git-scm.com/docs/git-config#Documentation/git-config.txt-remotepushDefault if present), falling back to `origin`.

Possibly, there needs to also be a split of remote to which refs are pushed and remote on which PRs are opened. Currently it isn't possible to create PRs to open-source repos like this one.

**Comment by ejoffe** [comment]
There are currently 7 places in spr.go that use **origin** hardcoded. It shouldn't be too hard to get this value from git config instead. Do you want to take on this change?

Opening a PR in a different repository is a cool idea. 
Will need to add a per branch spr configuration to tell which repository to make the pull request? or maybe keep it simple and just make it a repository wide configuration? 
Would 'spr update' also pull and rebase the code to the latest source repository?
As a whole this sounds like a cool feature.

**Comment by zsol** [comment]
More importantly IMO, supporting branch names other than `master` would be helpful for working on repositories that have [renamed their default branches](https://github.com/github/renaming)

**Comment by ejoffe** [comment]
I added remote and branch configuration to the repository config. Can we close this issue?
