### ISSUE TITLE
Allow subcommand shortcuts and error on invalid subcommand

### ISSUE THREAD

**Issue by sbienkow-ninja** [ejoffe/spr#89]
It'd be nice to be able to use subcommand shortcuts like `git spr u`. Makes it faster to use, without having to add custom git aliases.

Wha'ts more, current behavior that invalid subcommands cause `git spr status` to be triggered is super confusing. When I first switched to new version and did `git spr u`, status was shown without any error information. Took me a while to realize it didn't actually update my PR stack. IMO, running `git spr hell` should show an error that such subcommand doesn't exist and (maybe) also show help with list of all subcommands.

**Comment by ejoffe** [comment]
Done. 
I removed the base 'git spr' command, which used to run the status. Now the cli catches all errors. 
Added aliases: 'git spr s', 'git spr st', 'git spr u', 'git spr up'.
For merge you still have to type in the whole command.
